[package]
name = "Document Management"
version = "1.0.0"
authors = ["Taiwo Triumphant"]
upgrade_policy="compatible"


[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }

[addresses]
document_management = "0xc75c789d718e72421346243e19da574c9527292c10707cc92d5a3090aa473047"